### ISSUE TITLE
semantic issue with kung 

### ISSUE THREAD

**Issue by jldav1d** [remoo69/Compiler-Sheesh#46]
Produces an error with `kung` statement.

Code:
```
sheesh(){
    whole x = 10#
    kung(x == 10){
        whole x = 10#
    }
}
```

Error Message in terminal:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python312\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\David\Downloads\sheesh#\Compiler-Sheesh\Sheesh# Compiler.py", line 143, in run_parser
    errors, sem_err=parse.parse()
                  ^^^^^^^^^^^^^
  File "C:\Users\David\Downloads\sheesh#\Compiler-Sheesh\source\SyntaxAnalyzer\Parser.py", line 119, in parse
    self.semantic.analyze()
  File "C:\Users\David\Downloads\sheesh#\Compiler-Sheesh\source\SemanticAnalyzer\SemanticAnalyzer.py", line 119, in analyze
    self.routines[self.current_node.root]()
  File "C:\Users\David\Downloads\sheesh#\Compiler-Sheesh\source\SemanticAnalyzer\SemanticAnalyzer.py", line 253, in control_flow_statement
    if self.current_node.children[2].type=="Identifier" and self.current_node.children[0].value=="choose":
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AST' object has no attribute 'type'
```

**Comment by remoo69** [comment]
![image](https://github.com/remoo69/Compiler-Sheesh/assets/121857724/fbddefae-94bc-4e23-aa78-bec64a64b3f7)
fixed
