### ISSUE TITLE
semantic analyzer does not detect type mismatch

### ISSUE THREAD

**Issue by jldav1d** [remoo69/Compiler-Sheesh#48]
This applies to every data type.

Expected: Semantic Error
Actual: No Semantic Errors

Code:
```
sheesh(){
    whole a = 2#
    a = "hello"#
}
```

**Terminal Error Message:**
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python312\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\David\Downloads\sheesh#\Compiler-Sheesh\Sheesh# Compiler.py", line 140, in run_parser
    compiler.compile()
  File "C:\Users\David\Downloads\sheesh#\Compiler-Sheesh\source\core\compile.py", line 48, in compile
    self.codegen=CodeGeneration2(self.semantic.ast)
                                 ^^^^^^^^^^^^^^^^^
AttributeError: 'SemanticAnalyzer' object has no attribute 'ast'
```

**Comment by jldav1d** [comment]
Issue now resolved.

Error Message:
```
No Syntax Errors

Semantic Errors:
Line 3, Token 3: Variable Operand Type is Invalid for ""hello"", expected -> Variable of Type whole, Got Text
```
