### ISSUE TITLE
semantic issue when reassigning a variable

### ISSUE THREAD

**Issue by jldav1d** [remoo69/Compiler-Sheesh#55]
**Expected:**  Semantic Error
**Actual:** No Semantic Errors

Code:
```
sheesh(){
    whole a = 2#
    a = 2.5#
}
```

**Terminal Error Message**
```
Traceback (most recent call last):
  File "C:\Python312\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\David\Downloads\sheesh#\Compiler-Sheesh\Sheesh# Compiler.py", line 245, in compile
    compiler.compile()
  File "C:\Users\David\Downloads\sheesh#\Compiler-Sheesh\source\core\compile.py", line 43, in compile
    self.parser.parse()
  File "C:\Users\David\Downloads\sheesh#\Compiler-Sheesh\source\SyntaxAnalyzer\Parser.py", line 119, in parse
    self.semantic.analyze()
  File "C:\Users\David\Downloads\sheesh#\Compiler-Sheesh\source\SemanticAnalyzer\SemanticAnalyzer.py", line 123, in analyze
    self.routines[self.current_node.root]()
  File "C:\Users\David\Downloads\sheesh#\Compiler-Sheesh\source\SemanticAnalyzer\SemanticAnalyzer.py", line 169, in id_tail
    tail_map[self.current_node.children[0].root]()
  File "C:\Users\David\Downloads\sheesh#\Compiler-Sheesh\source\SemanticAnalyzer\SemanticAnalyzer.py", line 442, in assign
    value=self.semantic.create.eval_arithm(expr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\David\Downloads\sheesh#\Compiler-Sheesh\source\SemanticAnalyzer\SemanticAnalyzer.py", line 585, in eval_arithm
    return self.evaluate(eval)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\David\Downloads\sheesh#\Compiler-Sheesh\source\SemanticAnalyzer\SemanticAnalyzer.py", line 522, in evaluate
    operand_stack.append(int(token.value[1:-1]))
                         ^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '.'
```

**Comment by remoo69** [comment]
![image](https://github.com/remoo69/Compiler-Sheesh/assets/121857724/4d533e67-f2dc-4775-8732-7af7fc1cb81b)
cakes na
