### ISSUE TITLE
syntax analyzer issue

### ISSUE THREAD

**Issue by jldav1d** [remoo69/Compiler-Sheesh#63]
Cannot parse any value that is not _whole_ or _dec__.

**Example Code:**
```
sheesh(){
    sus x = cap#
}
```
Terminal Message:
```
Traceback (most recent call last):
  File "c:\Python312\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "source\Sheesh# Compiler.py", line 249, in compile
    compiler.compile()
  File "C:\Users\David\Downloads\sheesh#\Compiler-Sheesh\source\core\compile.py", line 47, in compile
    self.semantic.analyze()
  File "C:\Users\David\Downloads\sheesh#\Compiler-Sheesh\source\SemanticAnalyzer\SemanticAnalyzer.py", line 141, in analyze
    self.routines[self.current_node.root]()
  File "C:\Users\David\Downloads\sheesh#\Compiler-Sheesh\source\SemanticAnalyzer\SemanticAnalyzer.py", line 209, in var_or_seq_dec
    self.create.assign(self.current_node.children[1])
  File "C:\Users\David\Downloads\sheesh#\Compiler-Sheesh\source\SemanticAnalyzer\SemanticAnalyzer.py", line 526, in assign
    value=self.semantic.create.eval_arithm(expr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\David\Downloads\sheesh#\Compiler-Sheesh\source\SemanticAnalyzer\SemanticAnalyzer.py", line 697, in eval_arithm
    return self.evaluate(eval)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\David\Downloads\sheesh#\Compiler-Sheesh\source\SemanticAnalyzer\SemanticAnalyzer.py", line 625, in evaluate
    operand_stack.append(float(token.numerical_value))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'
```

**Comment by remoo69** [comment]
![Uploading image.png…]()
