### ISSUE TITLE
one line multiple declaration error

### ISSUE THREAD

**Issue by 1202DREAMSCAPE** [remoo69/Compiler-Sheesh#79]
without
![image](https://github.com/remoo69/Compiler-Sheesh/assets/88035813/ccd6f8a1-f525-45d9-ad36-1ee167fa0937)

with
![image](https://github.com/remoo69/Compiler-Sheesh/assets/88035813/459618c4-2fab-4464-b4dd-09d1064e4fc4)

without ule
![image](https://github.com/remoo69/Compiler-Sheesh/assets/88035813/3cf3162f-9053-48a7-8835-91a89316df08)

error
```
Semantic Analysis...
{'grr': Variable(grr, whole, None), 'roar': Variable(roar, whole, None)}
Generating code...
=
<class 'str'>
<class 'core.constants.whole'>
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Alden\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "c:\Users\Alden\Downloads\Compiler-Sheesh\source\Sheesh# Compiler.py", line 212, in run_semantic
    compiler.compile()
  File "c:\Users\Alden\Downloads\Compiler-Sheesh\source\core\compile.py", line 55, in compile
    self.codegen.generate_code()
  File "c:\Users\Alden\Downloads\Compiler-Sheesh\source\CodeGeneration\CodeGen.py", line 160, in generate_code
    self.routines[self.current_node.root]()
  File "c:\Users\Alden\Downloads\Compiler-Sheesh\source\CodeGeneration\CodeGen.py", line 237, in var_or_seq_dec
    Evaluators(self.current_node.leaves(), runtime_errors=self.runtime_errors, scope=self.current_scope, symbol_table=self.symbol_table).assign(id)
  File "c:\Users\Alden\Downloads\Compiler-Sheesh\source\CodeGeneration\Functionality\Evaluators.py", line 270, in assign
    value=const.py_types[id_ref.type](value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '5None16'

```

**Comment by jldav1d** [comment]
issue now resolved.

Code:
```
sheesh(){
    whole grr = 5, roar = 16#
    up("nasty $w $w $w", grr, roar, grr)#
}    
```
Terminal Output:
```
C:\Users\David\Downloads\sheesh#\Compiler-Sheesh>sheesh.exe                            
nasty 5 16 5
```
