### ISSUE TITLE
fails to print negative numbers

### ISSUE THREAD

**Issue by 1202DREAMSCAPE** [remoo69/Compiler-Sheesh#80]
![image](https://github.com/remoo69/Compiler-Sheesh/assets/88035813/0f599ed7-9d8a-44c1-8964-a101482bc28b)

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Alden\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "c:\Users\Alden\Downloads\Compiler-Sheesh\source\Sheesh# Compiler.py", line 265, in compile
    compiler.compile()
  File "c:\Users\Alden\Downloads\Compiler-Sheesh\source\core\compile.py", line 55, in compile
    self.codegen.generate_code()
  File "c:\Users\Alden\Downloads\Compiler-Sheesh\source\CodeGeneration\CodeGen.py", line 160, in generate_code
    self.routines[self.current_node.root]()
  File "c:\Users\Alden\Downloads\Compiler-Sheesh\source\CodeGeneration\CodeGen.py", line 237, in var_or_seq_dec
    Evaluators(self.current_node.leaves(), runtime_errors=self.runtime_errors, scope=self.current_scope, symbol_table=self.symbol_table).assign(id)
  File "c:\Users\Alden\Downloads\Compiler-Sheesh\source\CodeGeneration\Functionality\Evaluators.py", line 264, in assign
    self.symbol_table[id.value].assign(op=op, value=const.py_types[id_ref.type](value)[1:-1])                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^ 
TypeError: 'int' object is not subscriptable
```

**Comment by jldav1d** [comment]
Issue now works.

Terminal Output of program above:
```
C:\Users\David\Downloads\sheesh#\Compiler-Sheesh>sheesh.exe                            
-1029
```
